### ISSUE TITLE
[Crash]: Startup crash

### ISSUE THREAD

**Issue by TQCnoARosto** [Fuzss/mindfuldarkness#1]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.0

### Notes (Required)

Can't load the mod.

### Crash Report (Required)

https://pastebin.com/3cGuz28u

**Comment by Fuzss** [comment]
Thanks for reporting! Should be fixed in v4.0.1.
