### ISSUE TITLE
[Crash]: Crash on load with CTM

### ISSUE THREAD

**Issue by WenXin20** [Fuzss/mindfuldarkness#11]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

v1.19.2

### Mod Version (Required)

v4.0.8

### Notes (Required)

This seems to happen on load and crashes almost every time. It seems to be related to the ctm mod and when changing a resourcepack. 

### Crash Report (Required)

No crash report generated

### latest.log (Optional)

https://gist.github.com/WenXin20/e743ffdf1518d7aa2f52ccb0b6230c67#file-latest-log-L441

**Comment by Fuzss** [comment]
Thanks for reporting, fixed in latest versions.
