### ISSUE TITLE
[Bug]: Signs do not save text when mod is present

### ISSUE THREAD

**Issue by Dekamir** [Fuzss/mindfuldarkness#13]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.9

### Notes (Required)

In some (uncertain) configurations, when this mod is present, Signs (neither vanilla nor modded) save their text. Whatever written will be discarded upon a world reload or after some time.

I can provide any additional information needed.

Normally I have a clue about what's probably happening or how to recreate, but this time I'm clueless.
For research purposes, this is currently happening on my modpack.
Version without issues: [Figuratives 1.7 - CurseForge](https://legacy.curseforge.com/minecraft/modpacks/figuratives/files/4595610)
Version with issues: [Figuratives 1.8 - CurseForge](https://legacy.curseforge.com/minecraft/modpacks/figuratives/files/4597617)
Changelogs are strict, keeping a log of every single change.

**Mod Loader:** Fabric 0.14.21
**Launcher:** CurseForge Standalone
**JRE:** Launcher Bundled (Singleplayer), Eclipse Temurin 17 (Dedicated Server)
**OS:** Windows 10 22H2 x64 (en_US)

- Mod version irrelevant, tested older versions.
- Tried disabling other mods one-by-one, to no avail.
- Tried resetting mod's config.
- Tried disabling any other mod's conflictable config/mixin.

The gist contains:
- Minecraft latest.log with game start, world load, world exit, game exit; with this mod included.
- Mod list.

### latest.log (Optional)

https://gist.github.com/Dekamir/af9aae5ef5e6fe71427c659cc076762c

**Comment by Fuzss** [comment]
Hmm, it's not really possible for this mod to be responsible for actual data being lost. I can imagine maybe an issue with rendering text, but I'm pretty sure it can't go missing. The mod only affects asset loading, making it completely client-side. For actual data like sign text to be lost there would need to be a server-side component which there isn't.

**Comment by Dekamir** [comment]
It's more like the sign data is not sent to the server, at all. The client caches the sign text. 
For example, other players don't see what's written on the sign "edited". The text also disappears if that sign is somehow reloaded.

So I'm pretty sure this is completely client-side. I wish I could improve more information but this is an issue I have absolutely no idea about.
