### ISSUE TITLE
[Bug]: Dark theme sort of breaks the fire in the furnace

### ISSUE THREAD

**Issue by ParodyVerse** [Fuzss/mindfuldarkness#14]
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.19.4

### Mod Version (Required)

6.0.2

### Notes (Required)

![image](https://github.com/Fuzss/mindfuldarkness/assets/32398836/5a408a11-1175-494b-95d2-f15acffbf01b)
Mindful darkness causes coloring issues with fire in the furnace.

**Comment by Fuzss** [comment]
Try a different algorithm. Mindful Darkness uses a very wide approach which does have issue like this one. If none of the algorithms yields a good result you can exclude the furnace texture in the config file and manually apply a dark version with a resource pack.
