### ISSUE TITLE
[Suggestion]: Compatibility with DynamicCrosshair

### ISSUE THREAD

**Issue by Crendgrim** [Fuzss/mindfuldarkness#16]
### Suggestion (Required)

Greetings, I have received a report that MindfulDarkness doesn't work well with my mod DynamicCrosshair, as it darkens my crosshair texture: Crendgrim/DynamicCrosshairCompat#22

The fix appears to be to add `!dynamiccrosshair:textures/gui/crosshairs.png` to the default exclusion list. I could create a PR adding this. Unless there is a way for me to blacklist the texture from my mod? Let me know what you think is the best approach to this problem.

**Comment by Fuzss** [comment]
Thank you!
