### ISSUE TITLE
[Help/Bug]: How can I make your Mindful Darkness mod not darken your other mod Overflowing Bars?

### ISSUE THREAD

**Issue by IntM4rco** [Fuzss/mindfuldarkness#18]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v.8.0.2

### Notes (Required)

https://modrinth.com/mod/mindful-darkness
https://modrinth.com/mod/overflowing-bars
![2023-08-31_15 12 45](https://github.com/Fuzss/mindfuldarkness/assets/124934175/44b58530-dded-41fc-a429-495afeed5c8c)

**Comment by Fuzss** [comment]
Please check the configuration section on the Mindful Darkness page, it tells you how to exclude the texture from Overflowing Bars.

**Comment by IntM4rco** [comment]
I know how to do it, but I saw on the Github page of your mod Overflowing Bars that for Fabric you don't have any png/jpg files but only scripts. So only on Forge it seems to me that you can do it.

<img width="1259" alt="Screenshot 2023-08-31 alle 15 58 43" src="https://github.com/Fuzss/mindfuldarkness/assets/124934175/ba69a9b4-fb40-40b5-847d-4a0024b0bdaa">

**Comment by IntM4rco** [comment]
If you could then tell me the path to your mod I would appreciate it, because I can't find it.

**Comment by Fuzss** [comment]
You can check the Fabric mod jar to find the png file. The GitHub lay-out does not reflect the production jar.

**Comment by IntM4rco** [comment]
Ty so much.
