### ISSUE TITLE
[Bug]: Text changes colors on in-world signs

### ISSUE THREAD

**Issue by WenXin20** [Fuzss/mindfuldarkness#21]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

v1.20.1

### Mod Version (Required)

v8.0.2

### Notes (Required)

With Farmers Delight installed, glowing text on Canvas Hanging Signs change color when in any game menu with darkness enabled.
When exiting the menu, the text returns to normal like on vanilla signs
![image](https://github.com/Fuzss/mindfuldarkness/assets/12000593/bfb8097c-2052-42df-8043-c17c45975c3c)

![image](https://github.com/Fuzss/mindfuldarkness/assets/12000593/128e928f-226b-4595-9d49-e2449286001b)

**Comment by Fuzss** [comment]
Fixed in v8.0.3.
