### ISSUE TITLE
[Bug]: No Dark UI for inventory while wearing Quark backpack

### ISSUE THREAD

**Issue by stlouisn** [Fuzss/mindfuldarkness#22]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.9

### Notes (Required)

![2023-10-01_20 47 52](https://github.com/Fuzss/mindfuldarkness/assets/26663606/aede01f8-0b67-4ced-b1aa-cf0f319be62b)

**Comment by Fuzss** [comment]
There is a config option to control which textures / directories to affect. Make sure the backpack background is added in there.

**Comment by soleilan** [comment]
The Enchanting Table also doesn't work if you enable Quark Matrix Enchanting

**Comment by Fuzss** [comment]
You need to manually add texture paths in the config if they are not found. The mod page tells you how to do that.
When you have the paths feel free to post them here so they can be included in the next release by default.
