### ISSUE TITLE
[Bug]: Doesn't work with JEI

### ISSUE THREAD

**Issue by Wimblerrr** [Fuzss/mindfuldarkness#24]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.9

### Notes (Required)

- Install Mindful Darkness v4.0.9
- Install jei-1.19.2-forge-11.6.0.1018
- click "r" or "u" on an item to show crafting recipies

![2023-12-12_21 26 17](https://github.com/Fuzss/mindfuldarkness/assets/108224706/bea99964-6993-4fbb-8529-bdc6814f245c)

everything of the window should be changing, not just the small square like you see in the screenshot

**Comment by Fuzss** [comment]
You need to manually add texture paths in the config if they are not found. The mod page tells you how to do that.
When you have the paths required for JEI to work feel free to post them here so they can be included in the next release by default.
