### ISSUE TITLE
[Suggestion]: Better Archeology button location

### ISSUE THREAD

**Issue by OminousDiscovery** [Fuzss/mindfuldarkness#28]
### Mod Loader (Optional)

Forge

### Minecraft Version(s) (Optional)

1.20.1

### Suggestion (Required)

![2024-05-27_03 00 00](https://github.com/Fuzss/mindfuldarkness/assets/150559423/76940ae7-d8ed-49da-895d-2478031c4b80)
make the buttons go to the bottom of the screen for this ui

**Comment by Fuzss** [comment]
There is no way to detect where the texture actually starts. For menus with such unique behavior there is a blacklist in the config so it can be excluded from having the Mindful Darkness buttons.

**Comment by Fuzss** [comment]
Feel free to post the menu id when you find it so I can include it in the blacklist by default.
