### ISSUE TITLE
[Bug]: Essential text overlay

### ISSUE THREAD

**Issue by KIRUYXAN** [Fuzss/mindfuldarkness#32]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

v8.0.3

### Minimal Setup (Required)

Yes

### Notes (Required)

When using this mod with essential, all the text in it is crookedly layered, and adding to the exception does not help fix this, only disabling this mod via the sun/moon button helps
![image](https://github.com/user-attachments/assets/e64ab7b3-0f6c-4e93-83f2-a383b599c4ca)

### latest.log (Required)

https://mclo.gs/PYToGkc

**Comment by Fuzss** [comment]
See #15.
