### ISSUE TITLE
[Crash]: Startup crash

### ISSUE THREAD

**Issue by Apiterbakar** [Fuzss/mindfuldarkness#4]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.4.0

### Notes (Required)

when starting the game

### Crash Report (Required)

https://gist.github.com/Apiterbakar/010159aee8411c11d5b34f93ef8a9117

### latest.log (Optional)

https://gist.github.com/Apiterbakar/92c88b34cbabe1a992b8cbed47e24480

**Comment by Fuzss** [comment]
Duplicate of #1.

**Comment by Apiterbakar** [comment]
but different mod version
