### ISSUE TITLE
[Crash]: Crash with Continuity

### ISSUE THREAD

**Issue by SplendidAlakey** [Fuzss/mindfuldarkness#5]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.2

### Notes (Required)

1. Install [Continuity](https://modrinth.com/mod/continuity) and MindfulDarkness
2. Install [Torches Reimagined](https://www.curseforge.com/minecraft/texture-packs/torches-reimagined) and activate it
3. Create a world; if you chose anything but superflat and get particularly unlucky you'll crash at this step
4. Open creative inventory
5. Navigate to either the decoration blocks or global tab
6. Scroll down and crash

After a bit of looking around, I've come across this issue: https://github.com/PepperCode1/Continuity/issues/120, but it doesn't seem to be the same, as it was fixed by Fabric itself. Despite the logs blaming Continuity, I'm reporting here first, as it only happens when MindfulDarkness is installed.

The crash doesn't happen on Quilt with QSL.

### Crash Report (Required)

https://gist.github.com/SplendidAlakey/0a00e7a74ef8b60a5766fc73906a9ec9#file-crash-log

### latest.log (Optional)

https://gist.github.com/SplendidAlakey/0a00e7a74ef8b60a5766fc73906a9ec9#file-latest-log

**Comment by Fuzss** [comment]
Does the crash still happen in v4.0.4?

**Comment by SplendidAlakey** [comment]
Nope, thanks!
