### ISSUE TITLE
[Bug]: Breaks Continuity

### ISSUE THREAD

**Issue by SplendidAlakey** [Fuzss/mindfuldarkness#7]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.5

### Notes (Required)

1. Launch the game with Continuity and MindfulDarkness
2. Enable Continuity default resource pack or any other connected textures pack
3. Test any blocks, that are supposed to be connected, e.g. glass

Might be related to a fix done for #5, I only now noticed the issue, sorry.

![2023-05-06_10 40 51](https://user-images.githubusercontent.com/86702831/236613534-846d5aea-c8b6-488c-b706-dabacb18f383.png)
![2023-05-06_10 40 54](https://user-images.githubusercontent.com/86702831/236613540-030dcf1d-6259-40fe-8dd7-72d318873cc7.png)

### latest.log (Optional)

https://gist.github.com/SplendidAlakey/68a347a547906e949bb8c229ec73af02

**Comment by Fuzss** [comment]
Thanks once again for reporting! Fixed in v4.0.6, hopefully for good now.
