### ISSUE TITLE
[Bug]: Menu button fully overlaps with ModMenu button

### ISSUE THREAD

**Issue by SplendidAlakey** [Fuzss/mindfuldarkness#8]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.0.6

### Notes (Required)

1. Install MD and ModMenu, launch the game
2. Go into ModMenu's mod menu and change the `Mods Button` setting to to `Icon`
3. Go back to the main menu and observe that MD and ModMenu buttons are in exactly the same place

Visually, MindfulDarkness takes priority, but functionally ModMenu does, meaning if you click it, you'll just open the ModMenu.

![2023-05-22_06 17 52](https://github.com/Fuzss/mindfuldarkness/assets/86702831/8de9e1f5-64c2-4762-ac59-70b4532d1a44)
![2023-05-22_06 21 47](https://github.com/Fuzss/mindfuldarkness/assets/86702831/829d3dec-30b3-4a5b-8988-6172a22ed3a5)

**Comment by SplendidAlakey** [comment]
Just to add to this, it also overlaps with Completionist's Index, if ModMenu's button is set to either replace Realms or be below it, which is default. Adjacent is the only mode that avoids all conflicts at the moment.

Set to replace or put below:
![2023-05-22_08 20 55](https://github.com/Fuzss/mindfuldarkness/assets/86702831/2996a296-b99d-486d-b970-0c7297a46d4a)

Set to adjacent:
![2023-05-22_08 21 07](https://github.com/Fuzss/mindfuldarkness/assets/86702831/5ca1aaef-4ab8-4292-9cd3-54f90fc37968)

**Comment by Fuzss** [comment]
You really do find all the bugs, don't you haha, thanks! Well, fixed in v4.0.7. 

The dark mode button checks for overlap with another button, so it should work dynamically with all mods that add any button. Worst case; no free position is found, the button simply isn't added.

**Comment by SplendidAlakey** [comment]
Ha, yeah 😄Sorry if it sometimes gets a bit spammy, I just have a pretty hefty modpack and can usually find incompatibilities and whatnot fairly quickly.
