### ISSUE TITLE
[Suggestion]: Is it possible to make it work with ae2 and wireless ae2?

### ISSUE THREAD

**Issue by FearAK** [Fuzss/mindfuldarkness#9]
### Suggestion (Required)

The mod doesn't work on ae2 or wireless ae2, would really love to have it work with those if possible :)
Thank you for all your amazing mods, I use every single one of them! :D

**Comment by FearAK** [comment]
I figured I would add a few others that I notice that the mod isn't working on if you want me to while I'm playing

Anyway, I noticed it doesn't work with dank storage either.

**Comment by FearAK** [comment]
Oh I'm an idiot, my apologies >.< Just read the description in the mod and learned we have to manually add it. I'll see if my low iq brain is able to do it I guess x) Sorry about that.

**Comment by Fuzss** [comment]
No worries, haha, was about to tell you.

If you get it to work with the mods you mentioned feel free to share the paths you added to the config so I can include them by default.

**Comment by FearAK** [comment]
Will do :)
